function T = pack_stats_row(methodName, sessionName, xName, yName, n, r, ci_low, ci_high, p, r2)

    T = table( ...
        string(methodName), ...
        string(sessionName), ...
        string(xName), ...
        string(yName), ...
        n, r, ci_low, ci_high, p, r2, ...
        'VariableNames', {'Method','Session','X','Y','N','r','CI_low','CI_high','p','r2'});
end